import threading
import time
import unittest
from zjtest_utils import new_uac_get_access_token_uat
import requests


def get_uac_token_mps():
    uac_token = new_uac_get_access_token_uat('15011915716', '839639')
    print(uac_token)
    login_return_info = str(uac_token).split(",")
    return login_return_info


login_return_info = get_uac_token_mps()
accessToken = login_return_info[0]
userId = login_return_info[1]

# uat 广东愿景纺织有限公司
# orgCode = "660A412EEBEF428E89BA6521CC67225E"
# orgName = "广东愿景纺织有限公司"
# purchaseOrderNo = "PO663202901813"
# purchaseOrderId = "1582980217404977154"


# uat 上海辰景信息科技有限公司
orgCode = "D25A6AA1345240D99378CF9B6325BE1C"
orgName = "上海辰景信息科技有限公司"
purchaseOrderNo = "PO193266997648"
purchaseOrderId = "1583304892519309314"
purchaseOrderDetailId1 = "1583304896881385474"
purchaseOrderDetailId2 = "1583304896994631681"
purchaseOrderDetailId3 = "1583304897078517761"


# 新建发货通知单
def create_shippingNotice():
    url = 'https://uat-a.szzhijing.com/plmz-osp-pmc/shippingNotice/create'
    data = {
        "shippingNotice": {
            "transitWarehouse": "天津市采购在途仓",
            "destination": "天津市",
            "purchaseOrderNo": purchaseOrderNo,
            "departurePlace": "",
            "driverIdCard": "",
            "driverTelephone": "",
            "transportMethod": 1,
            "shippingNoticeStatusName": "",
            "warehouseCode": "W10154",
            "transporterId": "",
            "orgCode": orgCode,
            "expectedArrivalDate": "2022-10-28 00:00:00",
            "deliveryDate": "2022-10-28 00:00:00",
            "shippingNoticeStatus": "",
            "productType": "PB",
            "transporterName": "",
            "categoryPathCode": "PB:WS",
            "purchaseBusinessOrderNo": "",
            "salerName": "余冲uat01",
            "merchandiserName": "余冲uat01",
            "orgName": orgName,
            "categoryName": "坯布:纬编双面",
            "categoryId": "1400000000000000057:1400000000000000194",
            "purchaseOrderId": "1583304892519309314",
            "businessType": "B1",
            "supplierId": "005ECC77B2C84CA9B4FA6D925774BDFB",
            "supplierName": "李沁洋飞梭白条苏州0",
            "supplierAbbrName": "李沁洋飞梭白条苏州0",
            "supplierCode": "OU060796",
            "contractNo": purchaseOrderNo,
            "ownerId": "D25A6AA1345240D99378CF9B6325BE1C",
            "ownerCode": "D25A6AA1345240D99378CF9B6325BE1C",
            "ownerName": orgName,
            "agentName": "",
            "agentAbbrName": "",
            "agentId": "",
            "agentCode": "",
            "settlementType": "1",
            "warehouseId": "1560821997482536961",
            "warehouseSimpleName": "宜宾原料仓",
            "carrierUnderTaker": 1,
            "addressId": "120000000000,120100000000",
            "advanceAssignId": "",
            "shippingAssignPlanList": [

            ]
        },
        "shippingNoticeDetailList": [
            {
                "purchaseOrderDetailId": purchaseOrderDetailId1,
                "purchaseOrderId": purchaseOrderId,
                "batchNo": "李沁洋飞梭白条苏州0-20528637",
                "commodityId": "1582282930860793858",
                "commodityName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                "commodityCode": "PBWS09027001",
                "commodityAbbrName": "",
                "pieces": "",
                "brandName": "",
                "place": "",
                "spinningTechnology": "",
                "mainQuantity": 900000,
                "mainUnit": "1",
                "subQuantity": 900000,
                "subUnit": "9",
                "redeemMainQuantity": 0,
                "redeemSubQuantity": 0,
                "cabinetsNum": 1,
                "fcKgPrice": 1,
                "fcLbsPrice": 1,
                "vatRate": 13,
                "tariffRate": 0,
                "fcAmount": 900000,
                "canReceiveQuantity": 900000,
                "hcIncludeTaxPrice": 1,
                "hcVatAmount": 103539.8,
                "hcIncludeTaxAmount": 900000,
                "hcTariffAmount": 0,
                "storageMainQuantity": 0,
                "storageSubQuantity": 0,
                "originType": 0,
                "totalPayedMainQuantity": 0,
                "totalPayedHcIncludeTaxAmount": 0,
                "commodityInvoiceName": "",
                "commodityInvoiceSpec": "",
                "countMode": "",
                "supplierBatchNo": "",
                "warpWeftInfo": "",
                "qualityLevel": "AA",
                "extSize": "",
                "dyeingColorNo": "",
                "receiver": "",
                "limitPercentage": 0,
                "categoryId": "1400000000000000524",
                "categoryName": "抽针罗纹",
                "categoryPathCode": "PB:WS:09",
                "unDeliveryMainQuantity": 900000,
                "unDeliverySubQuantity": 900000,
                "deliveryMainQuantity": 44,
                "deliverySubQuantity": 44,
                "orgCode": orgCode,
                "orgName": orgName,
                "purchaseApplyItemId": "",
                "hcContractPrice": 1,
                "hcContractTotal": 900000,
                "availableDeliveryMainQuantity": 900000,
                "availableDeliverySubQuantity": 900000,
                "createTime": "2022-10-21 11:51:18",
                "createUserName": "余冲uat",
                "createUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                "createSystem": "FA98280021E64E8D9B8226E40E0151D7",
                "updateTime": "2022-10-21 11:59:23",
                "updateUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                "updateSystem": "FA98280021E64E8D9B8226E40E0151D7",
                "recordVersion": 2,
                "isDeleted": 0,
                "mainUnitName": "KG",
                "subUnitName": "条",
                "commodityBrand": "",
                "remark": "",
                "materialPlace": "",
                "commodityDyeingProcess": "",
                "productId": "1582282930827239425",
                "productCode": "PBWS09027",
                "productName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                "productAbbrName": "抽针罗纹",
                "relationDetailId": "",
                "distributeMainQuantity": 900000,
                "distributeSubQuantity": 900000,
                "color": "",
                "colorEn": "",
                "widthValue": "",
                "widthType": "",
                "widthUnit": "",
                "widthUnitName": "",
                "widthRemark": "",
                "gramWeight": "",
                "gramWeightRemark": "",
                "commoditySpec": "",
                "commoditySize": "",
                "commodityLength": "",
                "commodityHeight": "",
                "commodityNameEn": "",
                "price": 1,
                "receiptNo": "yuchong-uat",
                "packlist": [
                    {
                        "purchaseOrderDetailId": purchaseOrderDetailId1,
                        "purchaseOrderId": purchaseOrderId,
                        "batchNo": "李沁洋飞梭白条苏州0-20528637",
                        "commodityId": "1582282930860793858",
                        "commodityName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                        "commodityCode": "PBWS09027001",
                        "commodityAbbrName": "",
                        "pieces": "",
                        "brandName": "",
                        "place": "",
                        "spinningTechnology": "",
                        "mainQuantity": 900000,
                        "mainUnit": "1",
                        "subQuantity": 900000,
                        "subUnit": "9",
                        "redeemMainQuantity": 0,
                        "redeemSubQuantity": 0,
                        "cabinetsNum": 1,
                        "fcKgPrice": 1,
                        "fcLbsPrice": 1,
                        "vatRate": 13,
                        "tariffRate": 0,
                        "fcAmount": 900000,
                        "canReceiveQuantity": 900000,
                        "hcIncludeTaxPrice": 1,
                        "hcVatAmount": 103539.8,
                        "hcIncludeTaxAmount": 900000,
                        "hcTariffAmount": 0,
                        "storageMainQuantity": 0,
                        "storageSubQuantity": 0,
                        "originType": 0,
                        "totalPayedMainQuantity": 0,
                        "totalPayedHcIncludeTaxAmount": 0,
                        "commodityInvoiceName": "",
                        "commodityInvoiceSpec": "",
                        "countMode": "",
                        "supplierBatchNo": "",
                        "warpWeftInfo": "",
                        "qualityLevel": "AA",
                        "extSize": "",
                        "dyeingColorNo": "",
                        "receiver": "",
                        "limitPercentage": 0,
                        "categoryId": "1400000000000000524",
                        "categoryName": "抽针罗纹",
                        "categoryPathCode": "PB:WS:09",
                        "unDeliveryMainQuantity": 900000,
                        "unDeliverySubQuantity": 900000,
                        "deliveryMainQuantity": 44,
                        "deliverySubQuantity": 44,
                        "orgCode": orgCode,
                        "orgName": orgName,
                        "purchaseApplyItemId": "",
                        "hcContractPrice": 1,
                        "hcContractTotal": 900000,
                        "availableDeliveryMainQuantity": 900000,
                        "availableDeliverySubQuantity": 900000,
                        "createTime": "2022-10-21 11:51:18",
                        "createUserName": "余冲uat",
                        "createUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                        "createSystem": "FA98280021E64E8D9B8226E40E0151D7",
                        "updateTime": "2022-10-21 11:59:23",
                        "updateUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                        "updateSystem": "FA98280021E64E8D9B8226E40E0151D7",
                        "recordVersion": 2,
                        "isDeleted": 0,
                        "mainUnitName": "KG",
                        "subUnitName": "条",
                        "commodityBrand": "",
                        "remark": "",
                        "materialPlace": "",
                        "commodityDyeingProcess": "",
                        "productId": "1582282930827239425",
                        "productCode": "PBWS09027",
                        "productName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                        "productAbbrName": "抽针罗纹",
                        "relationDetailId": "",
                        "distributeMainQuantity": 900000,
                        "distributeSubQuantity": 900000,
                        "color": "",
                        "colorEn": "",
                        "widthValue": "",
                        "widthType": "",
                        "widthUnit": "",
                        "widthUnitName": "",
                        "widthRemark": "",
                        "gramWeight": "",
                        "gramWeightRemark": "",
                        "commoditySpec": "",
                        "commoditySize": "",
                        "commodityLength": "",
                        "commodityHeight": "",
                        "commodityNameEn": "",
                        "price": 1,
                        "receiptNo": "yuchong-uat",
                        "_id": 786864398802,
                        "receiptNoAssist": "f54cab41-99ea-8ebc-cbe5-a70d2258b33d",
                        "_defaultIndex": 1,
                        "_span": 1,
                        "_mergeIndex": 0,
                        "commodityPackageDesc": 1,
                        "_key": "f54cab41-99ea-8ebc-cbe5-a70d2258b33d1",
                        "items": [

                        ],
                        "viceUnit": "9",
                        "viceUnitName": "条"
                    }
                ],
                "_id": 786864398802,
                "receiptNoAssist": "f54cab41-99ea-8ebc-cbe5-a70d2258b33d",
                "_defaultIndex": 1,
                "_span": 1,
                "_mergeIndex": 0,
                "commodityPackageDesc": 1,
                "_key": "f54cab41-99ea-8ebc-cbe5-a70d2258b33d1"
            },
            {
                "purchaseOrderDetailId": purchaseOrderDetailId2,
                "purchaseOrderId": purchaseOrderId,
                "batchNo": "李沁洋飞梭白条苏州0-20528637",
                "commodityId": "1527197050326712322",
                "commodityName": "密根拉架1X1罗纹轻磨毛",
                "commodityCode": "PBWS03036001",
                "commodityAbbrName": "",
                "pieces": "",
                "brandName": "",
                "place": "",
                "spinningTechnology": "",
                "mainQuantity": 900000,
                "mainUnit": "1",
                "subQuantity": 900000,
                "subUnit": "1",
                "redeemMainQuantity": 0,
                "redeemSubQuantity": 0,
                "cabinetsNum": 1,
                "fcKgPrice": 1,
                "fcLbsPrice": 1,
                "vatRate": 13,
                "tariffRate": 0,
                "fcAmount": 900000,
                "canReceiveQuantity": 900000,
                "hcIncludeTaxPrice": 1,
                "hcVatAmount": 103539.8,
                "hcIncludeTaxAmount": 900000,
                "hcTariffAmount": 0,
                "storageMainQuantity": 0,
                "storageSubQuantity": 0,
                "originType": 0,
                "totalPayedMainQuantity": 0,
                "totalPayedHcIncludeTaxAmount": 0,
                "commodityInvoiceName": "",
                "commodityInvoiceSpec": "",
                "countMode": "",
                "supplierBatchNo": "",
                "warpWeftInfo": "",
                "qualityLevel": "AA",
                "extSize": "",
                "dyeingColorNo": "",
                "receiver": "",
                "limitPercentage": 0,
                "categoryId": "1400000000000000518",
                "categoryName": "密根拉架1X1罗纹",
                "categoryPathCode": "PB:WS:03",
                "unDeliveryMainQuantity": 900000,
                "unDeliverySubQuantity": 900000,
                "deliveryMainQuantity": 44,
                "deliverySubQuantity": 44,
                "orgCode": orgCode,
                "orgName": orgName,
                "purchaseApplyItemId": "",
                "hcContractPrice": 1,
                "hcContractTotal": 900000,
                "availableDeliveryMainQuantity": 900000,
                "availableDeliverySubQuantity": 900000,
                "createTime": "2022-10-21 11:51:18",
                "createUserName": "余冲uat",
                "createUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                "createSystem": "FA98280021E64E8D9B8226E40E0151D7",
                "updateTime": "2022-10-21 11:59:23",
                "updateUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                "updateSystem": "FA98280021E64E8D9B8226E40E0151D7",
                "recordVersion": 2,
                "isDeleted": 0,
                "mainUnitName": "KG",
                "subUnitName": "KG",
                "commodityBrand": "",
                "remark": "",
                "materialPlace": "",
                "commodityDyeingProcess": "",
                "productId": "1527197050297352193",
                "productCode": "PBWS03036",
                "productName": "5abZj涤纶POY三角网+20D氨纶低弹黄密根拉架1X1罗纹(轻磨毛)",
                "productAbbrName": "密根拉架1X1罗纹",
                "relationDetailId": "",
                "distributeMainQuantity": 900000,
                "distributeSubQuantity": 900000,
                "color": "",
                "colorEn": "",
                "widthValue": "",
                "widthType": "",
                "widthUnit": "",
                "widthUnitName": "",
                "widthRemark": "",
                "gramWeight": "",
                "gramWeightRemark": "",
                "commoditySpec": "",
                "commoditySize": "",
                "commodityLength": "",
                "commodityHeight": "",
                "commodityNameEn": "",
                "price": 1,
                "receiptNo": "yuchong-uat",
                "packlist": [
                    {
                        "purchaseOrderDetailId": purchaseOrderDetailId2,
                        "purchaseOrderId": purchaseOrderId,
                        "batchNo": "李沁洋飞梭白条苏州0-20528637",
                        "commodityId": "1527197050326712322",
                        "commodityName": "密根拉架1X1罗纹轻磨毛",
                        "commodityCode": "PBWS03036001",
                        "commodityAbbrName": "",
                        "pieces": "",
                        "brandName": "",
                        "place": "",
                        "spinningTechnology": "",
                        "mainQuantity": 900000,
                        "mainUnit": "1",
                        "subQuantity": 900000,
                        "subUnit": "1",
                        "redeemMainQuantity": 0,
                        "redeemSubQuantity": 0,
                        "cabinetsNum": 1,
                        "fcKgPrice": 1,
                        "fcLbsPrice": 1,
                        "vatRate": 13,
                        "tariffRate": 0,
                        "fcAmount": 900000,
                        "canReceiveQuantity": 900000,
                        "hcIncludeTaxPrice": 1,
                        "hcVatAmount": 103539.8,
                        "hcIncludeTaxAmount": 900000,
                        "hcTariffAmount": 0,
                        "storageMainQuantity": 0,
                        "storageSubQuantity": 0,
                        "originType": 0,
                        "totalPayedMainQuantity": 0,
                        "totalPayedHcIncludeTaxAmount": 0,
                        "commodityInvoiceName": "",
                        "commodityInvoiceSpec": "",
                        "countMode": "",
                        "supplierBatchNo": "",
                        "warpWeftInfo": "",
                        "qualityLevel": "AA",
                        "extSize": "",
                        "dyeingColorNo": "",
                        "receiver": "",
                        "limitPercentage": 0,
                        "categoryId": "1400000000000000518",
                        "categoryName": "密根拉架1X1罗纹",
                        "categoryPathCode": "PB:WS:03",
                        "unDeliveryMainQuantity": 900000,
                        "unDeliverySubQuantity": 900000,
                        "deliveryMainQuantity": 44,
                        "deliverySubQuantity": 44,
                        "orgCode": orgCode,
                        "orgName": orgName,
                        "purchaseApplyItemId": "",
                        "hcContractPrice": 1,
                        "hcContractTotal": 900000,
                        "availableDeliveryMainQuantity": 900000,
                        "availableDeliverySubQuantity": 900000,
                        "createTime": "2022-10-21 11:51:18",
                        "createUserName": "余冲uat",
                        "createUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                        "createSystem": "FA98280021E64E8D9B8226E40E0151D7",
                        "updateTime": "2022-10-21 11:59:23",
                        "updateUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                        "updateSystem": "FA98280021E64E8D9B8226E40E0151D7",
                        "recordVersion": 2,
                        "isDeleted": 0,
                        "mainUnitName": "KG",
                        "subUnitName": "KG",
                        "commodityBrand": "",
                        "remark": "",
                        "materialPlace": "",
                        "commodityDyeingProcess": "",
                        "productId": "1527197050297352193",
                        "productCode": "PBWS03036",
                        "productName": "5abZj涤纶POY三角网+20D氨纶低弹黄密根拉架1X1罗纹(轻磨毛)",
                        "productAbbrName": "密根拉架1X1罗纹",
                        "relationDetailId": "",
                        "distributeMainQuantity": 900000,
                        "distributeSubQuantity": 900000,
                        "color": "",
                        "colorEn": "",
                        "widthValue": "",
                        "widthType": "",
                        "widthUnit": "",
                        "widthUnitName": "",
                        "widthRemark": "",
                        "gramWeight": "",
                        "gramWeightRemark": "",
                        "commoditySpec": "",
                        "commoditySize": "",
                        "commodityLength": "",
                        "commodityHeight": "",
                        "commodityNameEn": "",
                        "price": 1,
                        "receiptNo": "yuchong-uat",
                        "_id": 634167575854,
                        "receiptNoAssist": "6e946e16-14d3-fa91-1093-431569b545ab",
                        "_defaultIndex": 2,
                        "_span": 1,
                        "_mergeIndex": 0,
                        "commodityPackageDesc": 1,
                        "_key": "6e946e16-14d3-fa91-1093-431569b545ab2",
                        "items": [

                        ],
                        "viceUnit": "1",
                        "viceUnitName": "KG"
                    }
                ],
                "_id": 634167575854,
                "receiptNoAssist": "6e946e16-14d3-fa91-1093-431569b545ab",
                "_defaultIndex": 2,
                "_span": 1,
                "_mergeIndex": 0,
                "commodityPackageDesc": 1,
                "_key": "6e946e16-14d3-fa91-1093-431569b545ab2"
            },
            {
                "purchaseOrderDetailId": purchaseOrderDetailId3,
                "purchaseOrderId": purchaseOrderId,
                "batchNo": "李沁洋飞梭白条苏州0-20528637",
                "commodityId": "1582282930860793858",
                "commodityName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                "commodityCode": "PBWS09027001",
                "commodityAbbrName": "",
                "pieces": "",
                "brandName": "",
                "place": "",
                "spinningTechnology": "",
                "mainQuantity": 800000,
                "mainUnit": "1",
                "subQuantity": 800000,
                "subUnit": "9",
                "redeemMainQuantity": 0,
                "redeemSubQuantity": 0,
                "cabinetsNum": 1,
                "fcKgPrice": 1,
                "fcLbsPrice": 1,
                "vatRate": 13,
                "tariffRate": 0,
                "fcAmount": 800000,
                "canReceiveQuantity": 800000,
                "hcIncludeTaxPrice": 1,
                "hcVatAmount": 92035.45,
                "hcIncludeTaxAmount": 800000,
                "hcTariffAmount": 0,
                "storageMainQuantity": 0,
                "storageSubQuantity": 0,
                "originType": 0,
                "totalPayedMainQuantity": 0,
                "totalPayedHcIncludeTaxAmount": 0,
                "commodityInvoiceName": "",
                "commodityInvoiceSpec": "",
                "countMode": "",
                "supplierBatchNo": "",
                "warpWeftInfo": "",
                "qualityLevel": "A",
                "extSize": "",
                "dyeingColorNo": "",
                "receiver": "",
                "limitPercentage": 0,
                "categoryId": "1400000000000000524",
                "categoryName": "抽针罗纹",
                "categoryPathCode": "PB:WS:09",
                "unDeliveryMainQuantity": 800000,
                "unDeliverySubQuantity": 800000,
                "deliveryMainQuantity": 44,
                "deliverySubQuantity": 44,
                "orgCode": orgCode,
                "orgName": orgName,
                "purchaseApplyItemId": "",
                "hcContractPrice": 1,
                "hcContractTotal": 800000,
                "availableDeliveryMainQuantity": 800000,
                "availableDeliverySubQuantity": 800000,
                "createTime": "2022-10-21 11:51:19",
                "createUserName": "余冲uat",
                "createUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                "createSystem": "FA98280021E64E8D9B8226E40E0151D7",
                "updateTime": "2022-10-21 11:59:23",
                "updateUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                "updateSystem": "FA98280021E64E8D9B8226E40E0151D7",
                "recordVersion": 2,
                "isDeleted": 0,
                "mainUnitName": "KG",
                "subUnitName": "条",
                "commodityBrand": "",
                "remark": "",
                "materialPlace": "",
                "commodityDyeingProcess": "",
                "productId": "1582282930827239425",
                "productCode": "PBWS09027",
                "productName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                "productAbbrName": "抽针罗纹",
                "relationDetailId": "",
                "distributeMainQuantity": 800000,
                "distributeSubQuantity": 800000,
                "color": "",
                "colorEn": "",
                "widthValue": "",
                "widthType": "",
                "widthUnit": "",
                "widthUnitName": "",
                "widthRemark": "",
                "gramWeight": "",
                "gramWeightRemark": "",
                "commoditySpec": "",
                "commoditySize": "",
                "commodityLength": "",
                "commodityHeight": "",
                "commodityNameEn": "",
                "price": 1,
                "receiptNo": "yuchong-uat",
                "packlist": [
                    {
                        "purchaseOrderDetailId": purchaseOrderDetailId3,
                        "purchaseOrderId": purchaseOrderId,
                        "batchNo": "李沁洋飞梭白条苏州0-20528637",
                        "commodityId": "1582282930860793858",
                        "commodityName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                        "commodityCode": "PBWS09027001",
                        "commodityAbbrName": "",
                        "pieces": "",
                        "brandName": "",
                        "place": "",
                        "spinningTechnology": "",
                        "mainQuantity": 800000,
                        "mainUnit": "1",
                        "subQuantity": 800000,
                        "subUnit": "9",
                        "redeemMainQuantity": 0,
                        "redeemSubQuantity": 0,
                        "cabinetsNum": 1,
                        "fcKgPrice": 1,
                        "fcLbsPrice": 1,
                        "vatRate": 13,
                        "tariffRate": 0,
                        "fcAmount": 800000,
                        "canReceiveQuantity": 800000,
                        "hcIncludeTaxPrice": 1,
                        "hcVatAmount": 92035.45,
                        "hcIncludeTaxAmount": 800000,
                        "hcTariffAmount": 0,
                        "storageMainQuantity": 0,
                        "storageSubQuantity": 0,
                        "originType": 0,
                        "totalPayedMainQuantity": 0,
                        "totalPayedHcIncludeTaxAmount": 0,
                        "commodityInvoiceName": "",
                        "commodityInvoiceSpec": "",
                        "countMode": "",
                        "supplierBatchNo": "",
                        "warpWeftInfo": "",
                        "qualityLevel": "A",
                        "extSize": "",
                        "dyeingColorNo": "",
                        "receiver": "",
                        "limitPercentage": 0,
                        "categoryId": "1400000000000000524",
                        "categoryName": "抽针罗纹",
                        "categoryPathCode": "PB:WS:09",
                        "unDeliveryMainQuantity": 800000,
                        "unDeliverySubQuantity": 800000,
                        "deliveryMainQuantity": 44,
                        "deliverySubQuantity": 44,
                        "orgCode": orgCode,
                        "orgName": orgName,
                        "purchaseApplyItemId": "",
                        "hcContractPrice": 1,
                        "hcContractTotal": 800000,
                        "availableDeliveryMainQuantity": 800000,
                        "availableDeliverySubQuantity": 800000,
                        "createTime": "2022-10-21 11:51:19",
                        "createUserName": "余冲uat",
                        "createUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                        "createSystem": "FA98280021E64E8D9B8226E40E0151D7",
                        "updateTime": "2022-10-21 11:59:23",
                        "updateUser": "446F7F89FDF1475A98BC89EB79B8FE3A",
                        "updateSystem": "FA98280021E64E8D9B8226E40E0151D7",
                        "recordVersion": 2,
                        "isDeleted": 0,
                        "mainUnitName": "KG",
                        "subUnitName": "条",
                        "commodityBrand": "",
                        "remark": "",
                        "materialPlace": "",
                        "commodityDyeingProcess": "",
                        "productId": "1582282930827239425",
                        "productCode": "PBWS09027",
                        "productName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                        "productAbbrName": "抽针罗纹",
                        "relationDetailId": "",
                        "distributeMainQuantity": 800000,
                        "distributeSubQuantity": 800000,
                        "color": "",
                        "colorEn": "",
                        "widthValue": "",
                        "widthType": "",
                        "widthUnit": "",
                        "widthUnitName": "",
                        "widthRemark": "",
                        "gramWeight": "",
                        "gramWeightRemark": "",
                        "commoditySpec": "",
                        "commoditySize": "",
                        "commodityLength": "",
                        "commodityHeight": "",
                        "commodityNameEn": "",
                        "price": 1,
                        "receiptNo": "yuchong-uat",
                        "_id": 46603579046,
                        "receiptNoAssist": "ef1aa8c9-3544-68ba-09d1-837b507ad4b0",
                        "_defaultIndex": 3,
                        "_span": 1,
                        "_mergeIndex": 0,
                        "commodityPackageDesc": 2,
                        "_key": "ef1aa8c9-3544-68ba-09d1-837b507ad4b03",
                        "items": [

                        ],
                        "viceUnit": "9",
                        "viceUnitName": "条"
                    }
                ],
                "_id": 46603579046,
                "receiptNoAssist": "ef1aa8c9-3544-68ba-09d1-837b507ad4b0",
                "_defaultIndex": 3,
                "_span": 1,
                "_mergeIndex": 0,
                "commodityPackageDesc": 2,
                "_key": "ef1aa8c9-3544-68ba-09d1-837b507ad4b03"
            }
        ]
    }

    header = {
        "Content-Type": "application/json",
        "accessToken": accessToken,
        "clientId": "FA98280021E64E8D9B8226E40E0151D7",
        "userId": userId
    }

    req = requests.post(url=url, headers=header, json=data).json()
    print(req)
    return req


shippingNotice = create_shippingNotice()
shippingNoticeId = shippingNotice["shippingNoticeId"]
shippingNoticeNo = shippingNotice["shippingNoticeNo"]
purchaseOrderId = shippingNotice["purchaseOrderId"]
purchaseOrderNo = shippingNotice["purchaseOrderNo"]


# 发货通知单提交
def submit_shippingNotice():
    url = 'https://uat-a.szzhijing.com/plmz-osp-pmc/shippingNotice/submit/' + shippingNoticeId
    data = {
        "shippingNoticeId": shippingNoticeId
    }

    header = {
        "Content-Type": "application/json",
        "accessToken": accessToken,
        "clientId": "FA98280021E64E8D9B8226E40E0151D7",
        "userId": userId
    }

    req = requests.post(url=url, headers=header, json=data)
    print(req)
    if req.text == "true":
        return "success"
    else:
        return "error"


# 发货通知单审核
def audit_shippingNotice():
    msg = submit_shippingNotice()
    print(msg)
    if msg == "error":
        return "提交发货通知第失败"
    url = 'https://uat-a.szzhijing.com/plmz-osp-pmc/shippingNotice/audit'
    data = {
        "shippingNoticeId": shippingNoticeId,
        "auditOperateType": 1
    }

    header = {
        "Content-Type": "application/json",
        "accessToken": accessToken,
        "clientId": "FA98280021E64E8D9B8226E40E0151D7",
        "userId": userId
    }

    req = requests.post(url=url, headers=header, json=data)
    if req.text == "true":
        print("发货通知单审核成功。")
        return "success"
    else:
        return "error"


# 生成入库单
def inboundOrder_saveAll():
    msg = audit_shippingNotice()
    if msg == "error":
        print("发货通知单审核失败了，入库流程不通。")
        return "error"
    url = 'https://uat-a.szzhijing.com/plmz-osp-wms/inboundOrder/saveAll'
    data = {
        "orgCode": orgCode,
        "inboundDate": "2022-10-20T08:35:37.934Z",
        "inboundWarehouseId": "1560821997482536961",
        "inboundOrderNo": "",
        "inboundType": "100",
        "inboundStatus": "",
        "dataSourceType": "",
        "bizOrderType": "40",
        "bizOrderNo": shippingNoticeNo,
        "supplierShippingOrderNo": "",
        "shipperName": "56供应商全称",
        "ownerName": orgName,
        "remark": "",
        "createUserName": "",
        "createTime": "",
        "auditUserName": "",
        "auditTime": "",
        "orgName": orgName,
        "shippingNoticeId": shippingNoticeId,
        "shippingNoticeNo": shippingNoticeNo,
        "shippingNoticeStatus": 40,
        "shippingNoticeStatusName": "已审核",
        "purchaseOrderId": purchaseOrderId,
        "purchaseOrderNo": purchaseOrderNo,
        "checkOrderId": "",
        "checkOrderNo": "",
        "needCheck": 0,
        "checkStatus": 1,
        "productType": "",
        "categoryPathCode": "PB:WS",
        "contractNo": "PO663202901813",
        "supplierId": "051EF5E5141E4597882B982C3846CEA7",
        "supplierCode": "56786",
        "supplierName": "56供应商全称",
        "supplierAbbrName": "",
        "businessType": "B1",
        "deliveryDate": "2022-10-26 00:00:00",
        "expectedArrivalDate": "2022-10-26 00:00:00",
        "departurePlace": "广州",
        "destination": "天津市",
        "onRoadWarehouseId": "1525312957896016853",
        "isDirectDistribute": 0,
        "distributionType": 0,
        "carrierUnderTaker": 2,
        "carrierUnderTakerName": "供应商",
        "transporterId": "",
        "transporterName": "",
        "transportMethod": 1,
        "transportMethodName": "汽运",
        "driverName": "",
        "driverTelephone": "",
        "driverIdCard": "",
        "driverLicensePlate": "",
        "ownerId": "660A412EEBEF428E89BA6521CC67225E",
        "ownerCode": "660A412EEBEF428E89BA6521CC67225E",
        "agentId": "",
        "agentName": "",
        "agentAbbrName": "",
        "warehouseId": "1560821997482536961",
        "warehouseCode": "W10154",
        "warehouseSimpleName": "宜宾原料仓",
        "advanceAssignId": "1582980258511212545",
        "productionOrderNos": "",
        "addressId": "120000000000,120100000000",
        "recordVersion": 0,
        "isDeleted": 0,
        "logisticTrace": "",
        "createUser": "",
        "createSystem": "FA98280021E64E8D9B8226E40E0151D7",
        "updateTime": "2022-10-20 16:12:40",
        "updateUser": "EFF93AE4EA534FE895FF38EE5CB5D13A",
        "updateUserName": "高婉运9",
        "updateSystem": "FA98280021E64E8D9B8226E40E0151D7",
        "settlementUnitId": "051EF5E5141E4597882B982C3846CEA7",
        "settlementUnitCode": "56786",
        "settlementUnitName": "56供应商全称",
        "settlementUnitAbbrName": "56供应商全称",
        "settlementType": "1",
        "originalCurrency": "CNY",
        "salesType": 1,
        "purchaseBusinessOrderNo": "YCPB1643704155",
        "salerName": "刘海伟",
        "merchandiserName": "刘海伟",
        "assignConfirmUserId": "",
        "assignConfirmUserName": "",
        "wayBillId": "1583008277792903169",
        "wayBillNo": "YS129457029932",
        "transporterCode": "",
        "agentCode": "",
        "bizOrderId": shippingNoticeId,
        "inboundWarehouseCode": "W10154",
        "inboundWarehouseName": "宜宾原料仓",
        "shipperId": "051EF5E5141E4597882B982C3846CEA7",
        "shipperCode": "051EF5E5141E4597882B982C3846CEA7",
        "settlementObjectId": "051EF5E5141E4597882B982C3846CEA7",
        "settlementObjectCode": "56786",
        "settlementObjectName": "56供应商全称",
        "mainOrderId": "1582980217404977154",
        "mainOrderNo": "PO663202901813",
        "inboundWarehouseType": 1,
        "receiveUserName": "王耀国",
        "receiveUserId": "CDE18DB469AF43A5B41933C3AE5C764C",
        "details": [
            {
                "noticeDetailId": "1583008267593117698",
                "shippingNoticeId": shippingNoticeId,
                "purchaseOrderDetailId": purchaseOrderDetailId,
                "purchaseOrderId": purchaseOrderId,
                "commodityId": "1582282930860793858",
                "commodityCode": "PBWS09027001",
                "commodityName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                "commodityAbbrName": "",
                "categoryId": "1400000000000000057:1400000000000000194",
                "categoryName": "坯布:纬编双面",
                "categoryPathCode": "PB:WS",
                "supplierBatchNo": "",
                "warpWeftInfo": "",
                "qualityLevel": "AA",
                "extSize": "",
                "dyeingColorNo": "",
                "receiver": "",
                "batchNo": "PO663202901813",
                "receiptNo": "PO663202901813",
                "receiptNoAssist": "40d99b91-a5ab-e64e-c164-ebe3b162bbd9",
                "deliveryMainQuantity": 9,
                "mainUnit": "1",
                "mainUnitName": "KG",
                "deliverySubQuantity": 9,
                "subUnit": "9",
                "subUnitName": "条",
                "price": 20,
                "deliveryAmount": 180,
                "commodityInvoiceName": "",
                "commodityInvoiceSpec": "",
                "commodityPackageDesc": 1,
                "commoditySingleWeight": 0,
                "commoditySingleBalls": 0,
                "ballWeight": 0,
                "advanceAssignId": "",
                "reduceMainQuantity": 9,
                "reduceSubQuantity": 0,
                "remark": "",
                "storageMainQuantity": 0,
                "storageSubQuantity": 0,
                "salesInventoryId": "1582995236342939650",
                "salesInventoryDetailId": "1582995236477157377",
                "orgCode": orgCode,
                "orgName": orgName,
                "createTime": "2022-10-20 16:12:37",
                "createUser": "EFF93AE4EA534FE895FF38EE5CB5D13A",
                "createUserName": "高婉运9",
                "createSystem": "FA98280021E64E8D9B8226E40E0151D7",
                "updateTime": "2022-10-20 16:12:41",
                "updateUser": "EFF93AE4EA534FE895FF38EE5CB5D13A",
                "updateUserName": "高婉运9",
                "updateSystem": "FA98280021E64E8D9B8226E40E0151D7",
                "recordVersion": 1,
                "isDeleted": 0,
                "vatRate": 13,
                "color": "",
                "colorEn": "",
                "widthValue": "",
                "widthType": "",
                "widthUnit": "",
                "widthUnitName": "",
                "widthRemark": "",
                "gramWeight": "",
                "gramWeightRemark": "",
                "commoditySpec": "",
                "commoditySize": "",
                "commodityLength": "",
                "commodityHeight": "",
                "commodityNameEn": "",
                "packlist": [
                    {
                        "packingOrderDetailId": "1583008267714752514",
                        "sequenceNo": 0,
                        "shippingNoticeId": shippingNoticeId,
                        "shippingNoticeNo": shippingNoticeNo,
                        "bizOrderDetailId": "1583008267593117698",
                        "mainOrderDetailId": "",
                        "commodityRootCategoryId": "1400000000000000057",
                        "commodityRootCategoryName": "坯布",
                        "commodityCategoryId": "1400000000000000057:1400000000000000194",
                        "commodityCategoryName": "坯布:纬编双面",
                        "commodityId": "1582282930860793858",
                        "commodityCode": "PBWS09027001",
                        "commodityName": "32S/2有机棉半精可漂可染+40S/2有机人棉紧密赛络纺定纺包漂包染抽针罗纹(蚀毛,烧毛)",
                        "commodityAbbrName": "",
                        "commodityColour": "",
                        "commodityModelStyle": "",
                        "sourceOrderType": 0,
                        "sourceOrderId": "",
                        "sourceOrderNo": "",
                        "inboundBatchNo": "",
                        "innerBatchNo": "",
                        "defectGrade": "0",
                        "qualityGrade": "",
                        "packageRemark": "",
                        "inboundItemCount": 0,
                        "inboundMainQuantity": 9,
                        "inboundViceQuantity": 9,
                        "mainUnit": "1",
                        "mainUnitName": "KG",
                        "viceUnit": "9",
                        "viceUnitName": "条",
                        "warehouseLocationCode": "",
                        "standardItemCount": 0,
                        "standardQuantity": 0,
                        "totalQty": 0,
                        "totalValue": 0,
                        "isDeleted": 0,
                        "orgCode": orgCode,
                        "orgName": orgName,
                        "createSystem": "FA98280021E64E8D9B8226E40E0151D7",
                        "createUser": "EFF93AE4EA534FE895FF38EE5CB5D13A",
                        "createUserName": "高婉运9",
                        "createTime": "2022-10-20 16:12:37",
                        "recordVersion": 0,
                        "packlistType": 1,
                        "batchNo": "PO663202901813",
                        "weightUnit": "2",
                        "lengthUnit": "8",
                        "items": [
                            {
                                "itemBatchNo": "PO663202901813-1",
                                "mainQuantity": "11.00",
                                "mainUnitName": "KG",
                                "weight": "",
                                "weightUnitName": "磅",
                                "length": "",
                                "lengthUnitName": "码",
                                "viceQuantity": 1,
                                "viceUnitName": "条",
                                "mainUnit": "1",
                                "viceUnit": "9",
                                "weightUnit": "2",
                                "lengthUnit": "8",
                                "index": 1,
                                "isDuplicate": "false"
                            },
                            {
                                "itemBatchNo": "PO663202901813-2",
                                "mainQuantity": "11.00",
                                "mainUnitName": "KG",
                                "weight": "",
                                "weightUnitName": "磅",
                                "length": "",
                                "lengthUnitName": "码",
                                "viceQuantity": 1,
                                "viceUnitName": "条",
                                "mainUnit": "1",
                                "viceUnit": "9",
                                "weightUnit": "2",
                                "lengthUnit": "8",
                                "isDuplicate": "false",
                                "index": 2
                            },
                            {
                                "itemBatchNo": "PO663202901813-3",
                                "mainQuantity": "11.00",
                                "mainUnitName": "KG",
                                "weight": "",
                                "weightUnitName": "磅",
                                "length": "",
                                "lengthUnitName": "码",
                                "viceQuantity": 1,
                                "viceUnitName": "条",
                                "mainUnit": "1",
                                "viceUnit": "9",
                                "weightUnit": "2",
                                "lengthUnit": "8",
                                "isDuplicate": "false",
                                "index": 3
                            }
                        ],
                        "mainQuantity": "33.00",
                        "viceQuantity": 3
                    },
                    {
                        "inboundOrderPacklistId": "",
                        "sequenceNo": "",
                        "packlistNo": "",
                        "batchNo": "PO663202901813",
                        "packlistType": 2,
                        "items": [
                            {
                                "itemBatchNo": "PO663202901813-4",
                                "mainQuantity": "99.00",
                                "mainUnitName": "KG",
                                "weight": "",
                                "weightUnitName": "磅",
                                "length": "",
                                "lengthUnitName": "码",
                                "viceQuantity": 1,
                                "viceUnitName": "条",
                                "mainUnit": "1",
                                "viceUnit": "9",
                                "weightUnit": "2",
                                "lengthUnit": "8",
                                "index": 1,
                                "isDuplicate": "false"
                            }
                        ],
                        "commodityColour": "",
                        "weightUnit": "2",
                        "lengthUnit": "8",
                        "mainQuantity": "99.00",
                        "viceQuantity": 1
                    }
                ],
                "inboundMainQuantity": 132,
                "inboundViceQuantity": 4,
                "commodityRootCategoryName": "坯布",
                "commodityRootCategoryCode": "PB",
                "ownerId": "660A412EEBEF428E89BA6521CC67225E",
                "ownerCode": "660A412EEBEF428E89BA6521CC67225E",
                "ownerName": orgName,
                "supplierId": "051EF5E5141E4597882B982C3846CEA7",
                "supplierName": "56供应商全称",
                "packageRemark": 1,
                "commodityColour": "",
                "commodityColorEn": "",
                "qualityGrade": "AA",
                "bizOrderDetailId": "1583008267593117698",
                "viceUnit": "9",
                "viceUnitName": "条",
                "sourceOrderNo": shippingNoticeNo,
                "sourceOrderId": shippingNoticeId,
                "inboundItemCount": 0,
                "planInboundMainQuantity": "9.00",
                "planInboundViceQuantity": 9,
                "supplierCode": "56786",
                "mainOrderDetailId": "1582980218554216450",
                "commodityCategoryCodePath": "PB:WS",
                "settlementType": "1",
                "inboundGrossWeight": 0,
                "warehouseLocationCode": "",
                "commoditySingleCount": 0,
                "oldSaleInventoryId": "1582995236342939650",
                "oldSaleInventoryDetailId": "1582995236477157377",
                "primeCost": 20,
                "purchaseBusinessType": "B1",
                "salesType": 1,
                "width": "",
                "grammage": ""
            }
        ]
    }

    header = {
        "Content-Type": "application/json",
        "accessToken": accessToken,
        "clientId": "FA98280021E64E8D9B8226E40E0151D7",
        "userId": userId
    }

    req = requests.post(url=url, headers=header, json=data).json()
    print(req)


if __name__ == '__main__':
    # for i in range(0,10):
    audit_shippingNotice()
    # t_shipmentsOrde_audit()
    # thread1 = threading.Thread(target=audit_shippingNotice, args=("thread1",))
    # thread2 = threading.Thread(target=inboundOrder_saveAll, args=("thread2",))
    # thread1.start()
    time.sleep(1)
    # thread2.start()
